CI workflows
smartcontractkit/chainlink-functions pull request #1
Opened 2023-11-30 16:38 UTC by vyzaldysanchez

2023-11-30 16:42 UTC, vyzaldysanchez commented on sonar-project.properties
> +sonar.projectKey=smartcontractkit_chainlink-functions
We will need to setup sonar here as well @momentmaker

2023-11-30 16:46 UTC, vyzaldysanchez commented
Not sure why aren't the other workflows/checks showing though...

2023-11-30 16:52 UTC, momentmaker commented
> Not sure why aren't the other workflows/checks showing though...

This PR is to `develop` but the workflows are targeting `master`.

2023-11-30 16:57 UTC, vyzaldysanchez commented
@jmank88 CI workflows will be targeting develop for this PR. If we want them to target any other branch, we can change that later.

2023-12-05 15:15 UTC, vyzaldysanchez commented
This is ready to be merged @jmank88, the linter is failing due to no code being available in this repo.

2023-12-05 16:04 UTC, jmank88 commented
The real code won't be ready for a while, so you can add some empty placeholders for now to make it green if you want to merge.

2023-12-05 18:33 UTC, vyzaldysanchez commented
All checks are now passing @jmank88.

2023-12-05 18:34 UTC, jmank88 approved these changes, later dismissed

2023-12-05 18:35 UTC, vyzaldysanchez commented
Apparently I'm not authorized to merge this...

2023-12-05 18:49 UTC, jmank88 commented
> Apparently I'm not authorized to merge this...

Neither am I!

2023-12-11 14:39 UTC, chudilka1 submitted a review, later dismissed

2023-12-11 14:39 UTC, chudilka1 commented on sonar-project.properties
> +sonar.projectKey=smartcontractkit_chainlink-functions_AYwh3yCRBZUeim9slLSP
Leave `smartcontractkit_chainlink-functions` (remove the unique ID, we keep projects without that suffix. It will require project key update in Sonar as well, let me know if help is needed)

2023-12-11 14:39 UTC, chudilka1 commented on .github/workflows/pull-request-develop.yml
> +    steps:
Sonar does not process here any reports that should come from linters/unit tests, only a basic analysis. So the expected would be reports uploaded when linter and tests are executed and then downloaded by the sonar-scan step...

2023-12-18 15:43 UTC, jmank88 submitted a review, later dismissed

2023-12-18 18:04 UTC, chudilka1 requested changes

2023-12-18 18:04 UTC, chudilka1 commented on .github/workflows/pull-request-develop.yml
> +    needs: [ci-lint, ci-test]
We do upload ci-test results, however, no linter ones. Can we add golangci-lint report to Sonar step as well (we do upload it already in the [ci-lint step](https://github.com/smartcontractkit/chainlink-functions/actions/runs/7187193475/job/19574253876?pr=1#step:2:255))?

We have to download golangci-lint report and get the corresponding Sonar variable set, like [here](https://github.com/smartcontractkit/chainlink/blob/develop/.github/workflows/ci-core.yml)

2023-12-22 18:06 UTC, chudilka1 approved these changes

2023-12-22 18:07 UTC, merged